server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Gateway,Avengers-Gateway

      routes:
        - id: avengers-api
          uri: http://localhost:8085
          predicates:
            - Path=/avengers-api/**

        - id: viloes-api
          uri: http://localhost:8086
          predicates:
            - Path=/viloes-api/**

        - id: batalha-api
          uri: http://localhost:8087
          predicates:
            - Path=/batalha-api/**
