server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    gateway:
      default-filters:
        # mant√©m headers corretos para swagger e redirects
        - PreserveHostHeader
      routes:
        # =========================
        # API AVENGERS
        # =========================
        - id: avengers-api
          uri: http://api-avengers:8080
          predicates:
            - Path=/avengers-api/**

        # =========================
        # API VILOES
        # =========================
        - id: viloes-api
          uri: http://api-viloes:8080
          predicates:
            - Path=/viloes-api/**

        # =========================
        # API BATALHA
        # =========================
        - id: batalha-api
          uri: http://api-batalha:8080
          predicates:
            - Path=/batalha-api/**
